// ---------- Pixel-art: palette + sprite maps + draw helpers ----------
// Each sprite is an array of strings; each char is one pixel. ' ' = transparent.
const PAL = {
  K:'#0a0a0f', d:'#1c1a2e', g:'#3a2f4a', G:'#5a4a6a', s:'#8a8aa0', S:'#c6c6d8',
  w:'#d8c8a8', W:'#f4ecd8', l:'#e6b892', L:'#f2d0b0',
  f:'#b7854a', F:'#e0c078', y:'#ffe08a',
  r:'#7a1f1f', R:'#c03636', o:'#e08030', O:'#ffcf5a',
  b:'#2a3a6a', B:'#4a6ab0', p:'#5a2a6a', P:'#a85cc8', M:'#d59cf0',
  e:'#2f6b3f', E:'#6fbf6a', c:'#4e9e92', C:'#7fd0c2',
  n:'#3a2a1a', N:'#6a4a2a', t:'#eef0e0', x:'#14101c', v:'#7fae3a',
  h:'#101018', // eye-shadow
};

const SPR = {
  // ---- Heroes ----
  hero_knight: [
    "    KKKK    ",
    "   KFFFFK   ",
    "   KsSSsK   ",
    "   KdhhdK   ",
    "   KssssK   ",
    "  KKssssKK  ",
    "  SsssssSS  ",
    "  KsSFFSsK  ",
    "  KssssssK  ",
    "   Ks  sK   ",
    "   Kd  dK   ",
    "   KK  KK   ",
  ],
  hero_rogue: [
    "    KKK     ",
    "   KgggK    ",
    "  KgggggK   ",
    "  KgKhKgK   ",
    "  KglllgK   ",
    "  KgggggK   ",
    " KgRffRgK   ",
    "  KgffgK    ",
    "  Kgg gK  Ks",
    "  Kg  gK KsK",
    "  Kd  dK Ks ",
    "  KK  KK    ",
  ],
  hero_mage: [
    "     K      ",
    "    KpK     ",
    "   KpppK    ",
    "  KppppppK  ",
    "   KgllgK   ",
    "   Kh  hK   ",
    "   KpPPpK  M",
    "  KpPPPPpKPM",
    "  KpPPPPpKM ",
    "  KppppppK  ",
    "   Kp  pK   ",
    "   KK  KK   ",
  ],
  hero_warden: [
    "    KKKK    ",
    "   KwwwwK   ",
    "  KwFFFFwK  ",
    "  KwllllwK  ",
    "  Kwh  hwK  ",
    "  KwwwwwwK  ",
    "  KcFccFcK  ",
    " FKcccccK   ",
    " FKcFFccK   ",
    " FKcccccK   ",
    "  Kc  cK    ",
    "  KK  KK    ",
  ],

  // ---- Enemies ----
  en_rat: [
    "            ",
    "            ",
    "  K      K  ",
    " KNK    KNK ",
    " KNNNKKNNNK ",
    " KNNNRNNNNKn",
    " KNttNNttNKn",
    "  KNNNNNNK n",
    "   KNNNNK   ",
    "   KN  NK   ",
    "            ",
    "            ",
  ],
  en_skeleton: [
    "    KKK     ",
    "   KtttK    ",
    "   KhthK    ",
    "   KtttK    ",
    "    KtK     ",
    "  KttttttK  ",
    "  tKtKtKt   ",
    "  KttttttK  ",
    "   Kt  tK   ",
    "   Kt  tK   ",
    "   Kt  tK   ",
    "   KK  KK   ",
  ],
  en_ghoul: [
    "   KK  KK   ",
    "  KeeKKeeK  ",
    "  KeOhhOeK  ",
    "  KeetteeK  ",
    "  KeeRReeK  ",
    " KeeeeeeeeK ",
    " KeEeeeeEeK ",
    " KeeeeeeeeK ",
    "  KeK  KeK  ",
    "  Ke    eK  ",
    "  Kv    vK  ",
    "  KK    KK  ",
  ],
  en_cultist: [
    "    KKKK    ",
    "   KrrrrK   ",
    "  KrrrrrrK  ",
    "  KrKOOKrK  ",
    "  KrrrrrrK  ",
    " KrrrrrrrrK ",
    " KrRrrrrRrK ",
    " KrrrOrrrrK ",
    " KrrrrrrrrK ",
    "  KrrrrrrK  ",
    "  Kr    rK  ",
    "  KK    KK  ",
  ],
  en_shade: [
    "    xxxx    ",
    "   xxddxx   ",
    "  xdddddxx  ",
    "  xdPKKPdx  ",
    "  xddddddx  ",
    " xdddddddx  ",
    " xxddddddxx ",
    "  xxddddxx  ",
    "  x xddx x  ",
    "   x xdx    ",
    "    x x x   ",
    "     x      ",
  ],
  en_wolf: [
    "            ",
    " K K        ",
    " KsKK   KK  ",
    " KsssKKKssK ",
    "KsOsssssssK ",
    "KssssssssssK",
    " KssssssssK ",
    " KssKssKssK ",
    " Ks KsK KsK ",
    "    K K K   ",
    "            ",
    "            ",
  ],
  en_boss: [
    "  K K  K K  ",
    " KtKKKKKKtK ",
    " KtwwwwwwtK ",
    " KwRKwwKRwK ",
    " KwwwwwwwwK ",
    "KKwwttttwwKK",
    "KFwwwwwwwwFK",
    "KFKwtttwKFK ",
    " KwwwwwwwwK ",
    " KwK KK KwK ",
    " Kw  KK  wK ",
    " KK  KK  KK ",
  ],

  // ---- Event NPCs ----
  npc_woman: [
    "    KKK     ",
    "   KNNNK    ",
    "  KNllllNK  ",
    "  KNlllllK  ",
    "  KNlKKlNK  ",  // hair over face
    "   KllllK   ",
    "   KsssK    ",
    "  KsSSSsK   ",
    "  KsSSSSsK  ",
    "  KsSSSSsK  ",
    "  KsSSSSsK  ",
    "  KK    KK  ",
  ],
  npc_eliza: [
    "   KRRRK    ",
    "  KRRRRRK   ",
    " KRRlllRRK  ",
    " KRlLLLlRK  ",
    " KRlhLhlRK  ",  // she looks straight back at you
    " KRRlLlRRK  ",
    "  KRgggRK   ",
    " KRgGGGgRK  ",
    " KgGGGGGgK  ",
    " KgGRRRGgK  ",  // a looter's red sash
    "  KgGGGgK   ",
    "  KK   KK   ",
  ],
  npc_silhouette: [
    "    xxx     ",
    "   xxxxx    ",
    "  xxxxxxx   ",
    "  xxRxRxx   ",  // faint red eyes
    "  xxxxxxx   ",
    "   xxxxx    ",
    "  xxxxxxx   ",
    " xxxxxxxxx  ",
    " xxxxxxxxx  ",
    " xxxxxxxxx  ",
    " xxxxxxxxx  ",
    " xx     xx  ",
  ],
  npc_beggar: [
    "    KKK     ",
    "   KnnnK    ",
    "   KnlnK    ",
    "   Khl hK   ",
    "   KnnnnK   ",
    "  KnNNNNnK  ",
    "  KnNfNNnK  ",
    " lKnNNNNnKl ",  // outstretched hands
    "  KnNNNNnK  ",
    "  KnN  NnK  ",
    "  Kn    nK  ",
    "  KK    KK  ",
  ],
  npc_cage: [
    "KsKsKsKsKsKs",
    "K e   e   sK",
    "s KeeeeeK  s",
    "K KeOhhOeK sK",
    "s KeetteeK s",
    "K Keeeeee  sK",
    "s KeEeeEe  s",
    "K  Keeee   sK",
    "s   Ke eK  s",
    "KsKsKsKsKsKs",
    " K        K ",
    " K        K ",
  ],
  npc_shrine: [
    "   KKKK     ",
    "  KGGGGK    ",
    "  KGttGK  O ",  // skull + candle flame
    "  KGhhGK Oo ",
    "  KGGGGK KnK",
    " KGGGGGGK n ",
    " KGssssGK   ",
    " KGsFFsGK   ",
    " KGssssGK   ",
    "KGGGGGGGGK  ",
    "KGGGGGGGGK  ",
    "KKKKKKKKKK  ",
  ],
  npc_mirror: [
    "  KFFFFFFK  ",
    "  KbBBBBbK  ",
    "  KBSbbBBK  ",
    "  KBbSbBBK  ",
    "  KBbbSbBK  ",
    "  KBbbbSBK  ",
    "  KBSbbbBK  ",
    "  KBbSbbBK  ",
    "  KbBBBBbK  ",
    "  KFFFFFFK  ",
    "   KF  FK   ",
    "   KK  KK   ",
  ],

  npc_merchant: [
    "    KKKK  O ",
    "   KppppK Oo",
    "  KpFFFFpKn ",
    "  KpllllpKn ",
    "  Kph  hpK  ",
    "  KpFFFFpK  ",
    " KpFyyyyFpK ",
    " KpFyFFyFpK ",  // gold-laden wares
    " KpFyyyyFpK ",
    " KpppppppK  ",
    "  Kp    pK  ",
    "  KK    KK  ",
  ],

  en_bat: [
    "            ",
    " K        K ",
    "KgK      KgK",
    "KggK KK KggK",
    "KgggKNNKgggK",
    " KggNNNNggK ",
    "  KgNRRNgK  ",
    "   KNNNNK   ",
    "    KNNK    ",
    "    K  K    ",
    "            ",
    "            ",
  ],
  en_ooze: [
    "            ",
    "            ",
    "    ee      ",
    "   KeeeK    ",
    "  KeEeeeK   ",
    " KeeehheeK  ",
    " KeEeeeEeK  ",
    "KeeeeeeeeeK ",
    "KeEeeEeeEeK ",
    "KeeeeeeeeeK ",
    " KKKKKKKKK  ",
    "            ",
  ],
  en_archer: [
    "    KKK   n ",
    "   KtttK n  ",
    "   KhthKn   ",
    "   KtttK n  ",
    "    KtKn  n ",
    "  KtttttKn  ",
    "  tKtKtn t  ",
    "  KtttnttK  ",
    "   Ktn tK   ",
    "   Kn  tK   ",
    "   nt  tK   ",
    "  nKK  KK   ",
  ],
  en_drowned: [
    "    KKK     ",
    "   KcccK    ",
    "   KchcK  b ",
    "   KcccK b  ",
    "  KcccccK b ",
    " KccCccccK  ",
    " KccccCccK b",
    " KcCcccccK  ",
    "  KcccccK b ",
    "   Kc cK    ",
    "   Kc cK  b ",
    "   KK KK    ",
  ],
  en_imp: [
    "  K      K  ",
    "  KoK  KoK  ",
    "   KooooK   ",
    "  KoOhhOoK  ",
    "  KooooooK  ",
    "   KooooK   ",
    "  KoOooOoK  ",
    " oKooooooKo ",
    "  KoooooK   ",
    "   Ko oK  o ",
    "   Ko oK oK ",
    "   KK KK K  ",
  ],
  en_rotpriest: [
    "    KKKK    ",
    "   KvvvvK   ",
    "  KvvvvvvK  ",
    "  KvKhhKvK  ",
    "  KvvttvvK N",
    " KvvvvvvvvKN",
    " KvEvvvvEvKN",
    " KvvvtvvvvKN",
    " KvvvvvvvvK ",
    "  KvvvvvvK N",
    "  Kv    vK  ",
    "  KK    KK  ",
  ],
  en_bonehound: [
    "            ",
    " t tt       ",
    " KtKK   KK  ",
    " KtttKKKttK ",
    "KtRtttttttK ",
    "KttttttttttK",
    " KttKttKttK ",
    " KttKttKttK ",
    " Kt KtK KtK ",
    "    K t K   ",
    "            ",
    "            ",
  ],

  // ---- Biome NPCs ----
  npc_sporewife: [
    "   eEEEe    ",
    "  EEvEvEE   ",
    " EEEEEEEEE  ",
    "   KlllK    ",
    "   Khl hK   ",
    "   KlllK    ",
    "  KeeeeeK   ",
    " lKeEvEeKl  ",
    "  KeeeeeK   ",
    "  KeEvEeK   ",
    "  Ke   eK   ",
    "  KK   KK   ",
  ],
  npc_ferryman: [
    "         n  ",
    "   KKKK  n  ",
    "  KggggK n  ",
    " KggggggKn  ",
    " KgKhhKgKn  ",
    " KggggggKn  ",
    " KgggggggKn ",
    " KggggggKn  ",
    " KggggggKn  ",
    "KKKKKKKKKK  ",
    " KbbbbbbK   ",
    "  KKKKKK    ",
  ],
  npc_smith: [
    "    KKK     ",
    "   KnnnK    ",
    "   KlllK    ",
    "   Khl hK   ",
    "   KlllK sN ",
    "  KfffffKsN ",
    " KffFfffKsN ",
    "  KfffffK   ",
    "  KffffK oO ",
    "  Kf  fK Oo ",
    "  KK  KK o  ",
    "     NNNNN  ",
  ],
  npc_bonechoir: [
    " KKK KKK KKK",
    "KgggKgggKggg",
    "KtttKtttKttt",
    "KhthKhthKhth",
    "KtttKtttKttt",
    "Kt tKt tKt t",
    "KgggKgggKggg",
    "KgggKgggKggg",
    "KgtgKgtgKgtg",
    "KgggKgggKggg",
    "KK KKK KKK K",
    "            ",
  ],
  npc_lamplighter: [
    "    KKK   O ",
    "   KwwwK KyK",
    "   KlllK KnK",
    "   KWlWK  n ",
    "   KlllK  n ",
    "   KnnnK  n ",
    "  KnnNnnK n ",
    "  KnnnnnKKn ",
    "  KnnnnnK   ",
    "  Kn   nK   ",
    "  Kn   nK   ",
    "  KK   KK   ",
  ],

  npc_overgrown: [
    "    KKKK    ",
    "   KFEFFK   ",
    "   KsSEsK   ",
    "   KdhEdK   ",
    "  EKssssK   ",
    "  KKsEssKK  ",
    "  SsEsssSS  ",
    "  KsSFESsK  ",
    " EKssssssK  ",
    "   KsE sK   ",
    "   Kd  dKe  ",
    "   KK  KK   ",
  ],
  npc_bride: [
    "    KKK     ",
    "   KWWWK    ",
    "   KWlWK    ",
    "   KhlhK    ",
    "   KlllK    ",
    "  KWWWWWK   ",
    "  KWWWWWK   ",
    " KWWBWWWK   ",
    " KWWWWWWK   ",
    " KWWWWWWKb  ",
    "  KWWWWK bb ",
    "   KKKK  b  ",
  ],
  npc_cindermonk: [
    "     o      ",
    "    OoO     ",
    "   KlllK    ",
    "   Khl hK   ",
    "   KlllK    ",
    "  KooooooK  ",
    " KoOooooOoK ",
    " KooooooooK ",
    " KoOoooOooK ",
    "  KKooooKK  ",
    "   Ko  oK   ",
    "  oKKKKKKo  ",
  ],
  npc_saint: [
    "   KtttK    ",
    "   KhthK    ",
    "   KtttK  y ",
    "    KtK  yFy",
    "  KttttttKy ",
    "  tKtKtKt   ",
    "  KtttttK   ",
    "   Kt tK  t ",
    "   Kt  K t  ",
    "  KKKKKKKKK ",
    "  KGGGGGGGK ",
    "  KKKKKKKKK ",
  ],
  npc_wolfmother: [
    " K K        ",
    " KsKK   KK  ",
    " KsssKKKssK ",
    "KsOsssssssK ",
    "KssssssssssK",
    " KssssssssK ",
    " KssssssssK ",
    " KssKssKssK ",
    " Ks sss  sK ",
    "   Kss Kss  ",
    "   KsK KsK  ",
    "    K   K   ",
  ],

  en_curator: [
    "    KtttK  y",
    "   KtWtWtK y",
    "   KthhthK y",
    "   KttttK Ky",
    "    KttK  Ny",
    "  KWWWWWWKN ",
    " KWtWWWWtWN ",
    " KWWWWWWWWN ",
    " KWtWWWWtWN ",
    " KWWWWWWWWN ",
    "  KW    WK N",
    "  KK    KK N",
  ],

  en_seamstress: [
    "    KKK   s ",
    "   KgggK s  ",
    "   KWhWK  s ",
    "   KgggK s  ",
    "  KggggggK  ",
    " sKgWggWgKs ",
    "  KggggggK s",
    " KgggggggK  ",
    " sKgWgWggKs ",
    "  Kgg  ggK  ",
    " s Kg  gK s ",
    "   KK  KK   ",
  ],
  en_starveling: [
    "   yFFFy    ",
    "   KtttK    ",
    "   KhthK    ",
    "   KtttK    ",
    "    KtK     ",
    "  KtttttK   ",
    "  tKtKtKt   ",
    "  KttttttK  ",
    "  KtKttKtK  ",
    "   Kt  tK   ",
    "   Kt  tK   ",
    "   KK  KK   ",
  ],
  en_velvet: [
    "    KKK     ",
    "   KrrrK    ",
    "  KrWWWrK   ",
    "  KrWhWrK   ",
    "  KrWWWrK   ",
    "   KrrrK    ",
    "  KrRrRrK   ",
    " KrrRrRrrK  ",
    " KrRrrrRrK  ",
    " KrrrrrrrK  ",
    "  KrrrrrK   ",
    "   KKKKK    ",
  ],

  en_butcher: [
    "   KffffK   ",
    "  KffffffK  ",
    "  KfKhhKfK  ",
    "  KffffffK s",
    " KfffrrfffKs",
    "KfRRrrrrRRKs",
    "KfRrrrrrrRKs",
    "KfRrrrrrrRss",
    " KRrrrrrrRKs",
    " KrrrrrrrrK ",
    " Kff    ffK ",
    " KK      KK ",
  ],

  en_captain: [
    "  y KFFK y  ",
    "   KFyyFK   ",
    "  KFFyyFFK  ",
    "   KwwwwK   ",
    "   KhwwhK   ",
    "  KFWWWWFK  ",
    " FKWFWWFWKF ",
    " FKWWFFWWKF ",
    " FKWWWWWWKF ",
    "  KWWFFWWK  ",
    "  KW    WK  ",
    "  KK    KK  ",
  ],

  // ---- Hunters: the Gilded Inquisition ----
  en_inquisitor: [
    "    KFFK    ",
    "   KFyyFK   ",
    "   KFyyFK   ",
    "   KwwwwK   ",
    "   KhwwhK   ",
    "  KFWWWWFK  ",
    "  KWFWWFWK  ",
    "  KWWFFWWK  ",
    "  KWWWWWWK  ",
    "  KWWFFWWK  ",
    "  KW    WK  ",
    "  KK    KK  ",
  ],
  en_witch_hunter: [
    "  KKKKKKKK  ",
    "   KnnnnK   ",
    "   KnnnnK   ",
    "  KKllllKK  ",
    "   Kh  hK   ",
    "   KllllK   ",
    "  KnNbbNnK  ",
    " sKnNbbNnK  ",
    " sKnnbbnnK  ",
    " sKnn  nnK  ",
    "  Kn    nK  ",
    "  KK    KK  ",
  ],
  en_penitent: [
    "   KKKK     ",
    "  KggggK    ",
    "  Kg  gK    ",
    "  KgRRgK    ",
    "  KGGGGGs   ",
    " KGGGGGGKs  ",
    " KGnnnnGKs  ",
    " KGGGGGGK   ",
    " KGnnnnGK   ",
    "  KG  GK    ",
    "  KG  GK    ",
    "  KK  KK    ",
  ],

  // ---- More event NPCs ----
  npc_gibbet: [
    "KKKKKKKK    ",
    "K      n    ",
    "K      n    ",
    "K     KwK   ",
    "K    Kh hK  ",
    "K     KwK   ",
    "K     KwK   ",
    "K    Kw wK  ",
    "K    K   K  ",
    "K           ",
    "K           ",
    "KKKKK       ",
  ],
  npc_child: [
    "            ",
    "    KKKK    ",
    "   KNNNNK   ",
    "   KllllK   ",
    "   KWhhWK   ",
    "   KllllK   ",
    "    KggK    ",
    "   KggggK   ",
    "   Kg  gK   ",
    "   Kg  gK   ",
    "            ",
    "            ",
  ],
  npc_fallen: [
    "            ",
    "   KsSsK    ",
    "   KdhdK    ",
    "   KssssK  s",
    "  KsSSSsK s ",
    "  KsSFSsKs  ",
    "  KsssssK   ",
    "  Kss sssK  ",
    "  Kd    dK  ",
    "  KK    KK  ",
    "            ",
    "            ",
  ],
  npc_lightbearer: [
    "    KyyK    ",
    "   KyWWyK   ",
    "   KWllWK   ",
    "   KhWWhK   ",
    "   KWWWWK   ",
    "  KyWWWWyK  ",
    "  KWWWWWWK  ",
    "  KWyWWyWK  ",
    "  KWWWWWWK  ",
    "  KWWWWWWK  ",
    "  KW    WK  ",
    "  KK    KK  ",
  ],

  // ---- Objects ----
  obj_chest: [
    "            ",
    "            ",
    "  KKKKKKKK  ",
    " KNNNNNNNNK ",
    " KNFFFFFFNK ",
    " KNFKyyKFNK ",
    " KNNNNNNNNK ",
    " KNFNNNNFNK ",
    " KNNNNNNNNK ",
    " KKKKKKKKKK ",
    "            ",
    "            ",
  ],
  obj_stairs: [
    "            ",
    " KKKKKKKKKK ",
    " KGGGGGGGGK ",
    " KKKKKKKGGK ",
    " KxxxxKGGGK ",
    " KxxxKGGGGK ",
    " KxxKGGGGGK ",
    " KxKGGGGGGK ",
    " KKGGGGGGGK ",
    " KKKKKKKKKK ",
    "            ",
    "            ",
  ],
  obj_torch: [
    "     O      ",
    "    OoO     ",
    "    ooo     ",
    "     o      ",
    "     N      ",
    "     N      ",
    "     N      ",
    "     N      ",
    "    KNK     ",
    "            ",
    "            ",
    "            ",
  ],
  obj_potion: [
    "    KK      ",
    "    KgK     ",
    "   KRRRK    ",
    "  KRRRRRK   ",
    "  KRWRRRK   ",
    "  KRRRRRK   ",
    "   KRRRK    ",
    "    KKK     ",
    "            ",
    "            ",
    "            ",
    "            ",
  ],

  // ---- Decorative props (never block movement; dressing per biome) ----
  obj_shelf: [
    " KKKKKKKKKK ",
    " KNNNNNNNNK ",
    " KNRWRFWRNK ",
    " KNRWRFWRNK ",
    " KNNNNNNNNK ",
    " KNFWRWFRNK ",
    " KNFWRWFRNK ",
    " KNNNNNNNNK ",
    " KNRWFRWRNK ",
    " KNNNNNNNNK ",
    " KKKKKKKKKK ",
    "            ",
  ],
  obj_statue: [
    "    KKKK    ",
    "   KsSSsK   ",
    "   KshhsK   ",
    "   KssssK   ",
    "  KsssssSK  ",
    "  KSsssssK  ",
    "  KsssssSK  ",
    "  KssssssK  ",
    "   KssssK   ",
    "  KGGGGGGK  ",
    " KGGGGGGGGK ",
    " KKKKKKKKKK ",
  ],
  obj_table: [
    "            ",
    "            ",
    " KKKKKKKKKK ",
    " KNNNNNNNNK ",
    " KNFFFFFFNK ",
    " KKKKKKKKKK ",
    "  KN    NK  ",
    "  KN    NK  ",
    "  KN    NK  ",
    "  KK    KK  ",
    "            ",
    "            ",
  ],
  obj_chair: [
    "            ",
    "   KKKKK    ",
    "   KNNNK    ",
    "   KNFNK    ",
    "   KNFNK    ",
    "   KNNNK    ",
    "  KKNNNKK   ",
    "  KNNNNNK   ",
    "  KKKKKKK   ",
    "   KN KN    ",
    "   KK KK    ",
    "            ",
  ],
  obj_urn: [
    "            ",
    "     KK     ",
    "    KggK    ",
    "   KGgggK   ",
    "  KGggggGK  ",
    "  KGggggGK  ",
    "  KGggggGK  ",
    "   KGgggK   ",
    "   KGgggK   ",
    "   KKKKKK   ",
    "            ",
    "            ",
  ],
  obj_sarcophagus: [
    "            ",
    "  KKKKKKKK  ",
    " KGGGGGGGGK ",
    " KGsSSSSsGK ",
    " KGsShhSsGK ",
    " KGsSSSSsGK ",
    " KGsSSSSsGK ",
    " KGGGGGGGGK ",
    " KGGGGGGGGK ",
    "  KKKKKKKK  ",
    "            ",
    "            ",
  ],
  obj_bones: [
    "            ",
    "            ",
    "            ",
    "   S   S    ",
    "  KSKKKSK   ",
    "  SWWWWWS   ",
    " KSWhWhWSK  ",
    "  SWWWWWS   ",
    "  KSSSSSK   ",
    "   S S S    ",
    "            ",
    "            ",
  ],
  obj_mushroom: [
    "            ",
    "            ",
    "    KKK     ",
    "   KPPPK    ",
    "  KPMPPMPK  ",
    "  KPPPPPPK  ",
    "   KKKKK    ",
    "    KtK     ",
    "    KtK     ",
    "   KKtKK    ",
    "            ",
    "            ",
  ],
  obj_barrel: [
    "            ",
    "   KKKKKK   ",
    "  KNFFFFNK  ",
    "  KNFFFFNK  ",
    "  KNNNNNNK  ",
    "  KNFFFFNK  ",
    "  KNFFFFNK  ",
    "  KNNNNNNK  ",
    "  KNFFFFNK  ",
    "   KKKKKK   ",
    "            ",
    "            ",
  ],
  obj_stump: [
    "            ",
    "            ",
    "     n      ",
    "   KnNnK    ",
    "  KnNNNnK   ",
    "  KNNnNNK   ",
    "  KnNNNnK   ",
    "  KNNNNNK   ",
    "  KnNNNnK   ",
    "  KKKKKKK   ",
    "            ",
    "            ",
  ],
  obj_brazier: [
    "     O      ",
    "    OoO     ",
    "   OoyoO    ",
    "    ooo     ",
    "  KGGGGGGK  ",
    "  KGGGGGGK  ",
    "   KGGGGK   ",
    "    KGGK    ",
    "    KGGK    ",
    "   KGGGGK   ",
    "  KKKKKKKK  ",
    "            ",
  ],
};

const Sprites = {
  SPR, PAL,
  // draw a sprite at device pixel (px,py) with per-pixel size `scale`
  draw(ctx, name, px, py, scale, opts){
    const s = SPR[name];
    if (!s) return;
    opts = opts || {};
    const tint = opts.tint;      // force all pixels to this color
    const alpha = opts.alpha == null ? 1 : opts.alpha;
    if (alpha !== 1) ctx.globalAlpha = alpha;
    for (let row = 0; row < s.length; row++){
      const line = s[row];
      for (let col = 0; col < line.length; col++){
        const ch = line[col];
        if (ch === ' ') continue;
        const color = tint || PAL[ch];
        if (!color) continue;
        ctx.fillStyle = color;
        ctx.fillRect(px + col * scale, py + row * scale, scale, scale);
      }
    }
    if (alpha !== 1) ctx.globalAlpha = 1;
  },
  // render a sprite centered onto a small canvas (used for cards/art)
  toCanvas(canvas, name, scale, opts){
    const ctx = canvas.getContext('2d');
    ctx.imageSmoothingEnabled = false;
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    const s = SPR[name];
    const w = 12 * scale, h = 12 * scale;
    const ox = Math.floor((canvas.width - w) / 2);
    const oy = Math.floor((canvas.height - h) / 2);
    this.draw(ctx, name, ox, oy, scale, opts);
  }
};
